language: elixir
addons:
  chrome: stable

elixir:
    - 1.5.0
env:
  - NODE_VERSION="7.7.2"
before_install:
  - nvm install $NODE_VERSION
before_script:
  - npm install -g brunch
  - cd assets && npm install && brunch build --production
  - cd .. && mix phx.digest
dist: trusty
